### ISSUE TITLE
Line 159 Is Looking for hs_color, but is receiving rgb_color

### ISSUE THREAD

**Issue by zimmra** [yangqian/hass-gelight#2]
I have this spun up in a temporary setup, so this issue is separate from the other that I've posted

I get the following error thrown

```
ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 619, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/light/__init__.py", line 438, in state_attributes
    if supported_features & SUPPORT_COLOR and self.hs_color:
  File "/home/homeassistant/.homeassistant/custom_components/gelight/light.py", line 159, in hs_color
    return tuple(self.red,self.green,self.blue)
TypeError: tuple expected at most 1 argument, got 3
```

From what I can tell it is looking for hs_color which would be hue & saturation, but it is receiving rgb

There is color_RGB_to_hs available in color.py from homeassistant, but I am not sure how to modify the gelight script to look use this

**Comment by yangqian** [comment]
I have corrected the error. Please checkout the code again. But as I don't have a RGB light. I am not sure if it will work.

**Comment by zimmra** [comment]
> I have corrected the error. Please checkout the code again. But as I don't have a RGB light. I am not sure if it will work.

Thanks for quick response, but doesn't like it. Error slightly changed

```
ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139809237539328] color_hs_to_RGB() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1486, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 516, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/light/__init__.py", line 441, in state_attributes
    data[ATTR_RGB_COLOR] = color_util.color_hs_to_RGB(*hs_color)
TypeError: color_hs_to_RGB() takes 2 positional arguments but 3 were given
```

**Comment by zimmra** [comment]
Progress!
I changed it from
```
    def hs_color(self):
        """Return the hs_color of the light."""
        return (self.red,self.green,self.blue)
```

to

```
    def rgb_color(self):
        """Return the hs_color of the light."""
        return tuple(self.red,self.green,self.blue)
```
and I now have control of the lights and their color temperature

When attempting to change the color I do get some errors and nothing happens

error:
```
ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139694556158704] not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1486, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 499, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 536, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/light/__init__.py", line 230, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/home/homeassistant/.homeassistant/custom_components/gelight/light.py", line 200, in async_turn_on
    await self.hass.async_add_executor_job(self.set_rgb,kwargs[ATTR_HS_COLOR])
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/gelight/light.py", line 257, in set_rgb
    red, green, blue= hs_color
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by yangqian** [comment]
> Progress!
> I changed it from
> 
> ```
>     def hs_color(self):
>         """Return the hs_color of the light."""
>         return (self.red,self.green,self.blue)
> ```
> 
> to
> 
> ```
>     def rgb_color(self):
>         """Return the hs_color of the light."""
>         return tuple(self.red,self.green,self.blue)
> ```
> 
> and I now have control of the lights and their color temperature
> 
> When attempting to change the color I do get some errors and nothing happens
> 
> error:
> 
> ```
> ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139694556158704] not enough values to unpack (expected 3, got 2)
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
>     await hass.services.async_call(
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1451, in async_call
>     task.result()
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1486, in _execute_service
>     await handler.job.target(service_call)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
>     await self.hass.helpers.service.entity_service_call(
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 499, in entity_service_call
>     future.result()  # pop exception if have
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 664, in async_request_call
>     await coro
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 536, in _handle_entity_call
>     await result
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/light/__init__.py", line 230, in async_handle_light_on_service
>     await light.async_turn_on(**params)
>   File "/home/homeassistant/.homeassistant/custom_components/gelight/light.py", line 200, in async_turn_on
>     await self.hass.async_add_executor_job(self.set_rgb,kwargs[ATTR_HS_COLOR])
>   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/homeassistant/.homeassistant/custom_components/gelight/light.py", line 257, in set_rgb
>     red, green, blue= hs_color
> ValueError: not enough values to unpack (expected 3, got 2)
> ```

Could you check if the correct code works?

**Comment by zimmra** [comment]
Your recent update fixed it, I have accurate control over the lamps now. This includes temp, color, brightness, and on/off.
